# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gpswebsock"
version = "1.0.0"
description = "GPS endpoint exposed over WebSocket"
license = {text = "Apache-2.0"}
authors = [
    {name = "TII (SSRC) and the Ghaf contributors"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Communications",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.11"
dependencies = [
    "websockets>=12.0",
]

[project.urls]
Homepage = "https://github.com/tiiuae/ghafpkgs"

[project.scripts]
gpswebsock = "gpswebsock.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/gpswebsock"]

[dependency-groups]
dev = []
