# Copyright 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vinotify"
version = "1.0.0"
description = "Virtual machine file system notification service using inotify"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "TII (SSRC) and the Ghaf contributors"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Systems Administration",
    "Topic :: System :: Filesystems",
    "Topic :: System :: Monitoring",
]
requires-python = ">=3.11"
dependencies = [
    "inotify_simple>=1.3.5",
]

[project.scripts]
vinotify = "vinotify.vinotify:main"

[tool.hatch.build.targets.wheel]
packages = ["vinotify"]

[tool.uv]
dev-dependencies = []